config/routes.rb
Print::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "pages/home"
  root :to => 'pages#home'
  get "admin/login"

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :addressable_type, :city, :state, :street, :zip
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :addressable_id, :name
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :completed, :customer_id, :description, :end_date, :name, :start_date, :whiteboard, :number

  validates :number, presence: true, numericality: { integer_only: true, greater_than_or_equal_to: 0 }
end

app/models/order_category.rb
class OrderCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/order_priority.rb
class OrderPriority < ActiveRecord::Base
  attr_accessible :name, :priority
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  attr_accessible :active, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/addresses/_form.html.erb
<%=
form.inputs "Address" do 
  form.semantic_fields_for :address do |address| 
    address.inputs :class => "" do 
      address.input :street 
      address.input :city 
      address.input :state, :as => :select, :collection => States::all.invert 
      address.input :zip, as: :string
    end 
  end 
end 
%>

app/views/addresses/_show.html.erb
<div class="panel">
    <h3>Address</h3>
    <div class="panel_contents">
      <div id="attributes_table_employee_1" class="attributes_table">
        <table cellspacing="0" cellpadding="0" border="0">
          <tbody>
          <tr>
            <th>Street</th>
            <td><%= address.street.blank? ? raw('<span class="empty">Empty</span>') : address.street %></td>
          </tr>
          <tr>
            <th>City</th>
            <td><%= address.city.blank? ? raw('<span class="empty">Empty</span>') : address.city %></td>
          </tr>
          <tr>
            <th>State</th>
            <td><%= address.state.blank? ? raw('<span class="empty">Empty</span>') : address.state %></td>
          </tr>
          <tr>
            <th>Zip</th>
            <td><%= address.zip.blank? ? raw('<span class="empty">Empty</span>') : address.zip %></td>
          </tr>
        </tbody></table>
      </div>
    </div>
  </div>

app/views/customers/_form.html.erb
<%=
semantic_form_for @customer, :builder => ActiveAdmin::FormBuilder do |f| 
  f.inputs "Customer Information" do 
    f.input :name 
		f.input :email
		f.input :phone
  render :partial => "addresses/form", :locals => { :form => f } 
  f.buttons 
end 
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Print</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<%= yield %>

	</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to 'Sign In', new_admin_user_session_path  %>